# Generated by Django 5.0.2 on 2024-02-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=4)),
                ('cost', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FactoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=4)),
                ('cost', models.IntegerField()),
                ('maximum_production', models.IntegerField()),
                ('production_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=6)),
                ('username', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LabourCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=4)),
                ('cost', models.IntegerField()),
                ('labour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PayOutCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=4)),
                ('free_flow_payout', models.IntegerField()),
                ('crude_payout', models.IntegerField()),
                ('iodized_payout', models.IntegerField()),
                ('payout_type', models.CharField(choices=[('normal', 'normal'), ('fire', 'fire'), ('rain', 'rain'), ('strike', 'strike'), ('no_buyer', 'no_buyer')], max_length=20)),
            ],
        ),
    ]
