# Generated by Django 5.0.2 on 2024-02-10 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_factorycard_factory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='payoutcard',
            name='payout_type',
        ),
        migrations.AddField(
            model_name='payoutcard',
            name='crude_payout_type',
            field=models.CharField(choices=[('normal', 'normal'), ('fire', 'fire'), ('rain', 'rain'), ('strike', 'strike'), ('no_buyer', 'no_buyer')], default='normal', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payoutcard',
            name='free_flow_payout_type',
            field=models.CharField(choices=[('normal', 'normal'), ('fire', 'fire'), ('rain', 'rain'), ('strike', 'strike'), ('no_buyer', 'no_buyer')], default='normal', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payoutcard',
            name='iodized_payout_type',
            field=models.CharField(choices=[('normal', 'normal'), ('fire', 'fire'), ('rain', 'rain'), ('strike', 'strike'), ('no_buyer', 'no_buyer')], default='normal', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='main.gamesession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_player', to='main.gamesession')),
            ],
        ),
    ]
