# Generated by Django 5.0.2 on 2024-02-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_gamesession_username_gamesession_player_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFactory',
            new_name='PlayerFactory',
        ),
    ]
