# Generated by Django 5.0.2 on 2024-02-16 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_game_id_gamesession_game_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_player', to='main.player'),
        ),
    ]
