# Generated by Django 5.0.2 on 2024-02-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_gameplayer_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='game_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
